version: "3.9"

services:
  # POSTGRES
  database:
    image: postgres:17-alpine
    container_name: statter-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: statter
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # RABBITMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: statter-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network

  # REDIS
  redis:
    image: redis:7.0-alpine
    container_name: statter-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:

networks:
  app-network:
